import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontSize: {
        "display-xl": ["56px",{"fontWeight":"700","lineHeight":"1.05","letterSpacing":"-2.0px"}],
        "display-lg": ["40px",{"fontWeight":"700","lineHeight":"1.1","letterSpacing":"-1.2px"}],
        "display-md": ["28px",{"fontWeight":"600","lineHeight":"1.2","letterSpacing":"-0.6px"}],
        "heading-lg": ["22px",{"fontWeight":"600","lineHeight":"1.3","letterSpacing":"-0.3px"}],
        "heading-md": ["18px",{"fontWeight":"600","lineHeight":"1.4","letterSpacing":"-0.2px"}],
        "heading-sm": ["15px",{"fontWeight":"600","lineHeight":"1.4","letterSpacing":"0"}],
        "body-lg": ["16px",{"fontWeight":"400","lineHeight":"1.6","letterSpacing":"0"}],
        "body-md": ["14px",{"fontWeight":"400","lineHeight":"1.5","letterSpacing":"0"}],
        "body-sm": ["13px",{"fontWeight":"400","lineHeight":"1.5","letterSpacing":"0"}],
        "label-uppercase": ["11px",{"fontWeight":"600","lineHeight":"1.3","letterSpacing":"0.8px"}],
        "caption": ["12px",{"fontWeight":"400","lineHeight":"1.4","letterSpacing":"0"}],
        "button": ["14px",{"fontWeight":"500","lineHeight":"1.0","letterSpacing":"0"}],
      },
      spacing: {
        "xxs": "4px",
        "xs": "8px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "xxl": "48px",
        "section": "80px",
      },
      colors: {

        "primary-hover": "#7986d8",
        "primary-active": "#4a5ab0",
        "on-primary": "#ffffff",
        "success": "#27c45e",
        "success-muted": "#0f2a1a",
        "warning": "#f59e0b",
        "warning-muted": "#2a1e00",
        "danger": "#e5534b",
        "danger-muted": "#2a0f0f",
        "info": "#3b96db",
        "info-muted": "#0a1e30",
        "canvas": "#0a0a0b",
        "canvas-soft": "#111113",
        "surface-1": "#161618",
        "surface-2": "#1e1e21",
        "surface-3": "#252528",
        "surface-4": "#2e2e32",
        "hairline": "#2a2a2f",
        "hairline-strong": "#3a3a42",
        "hairline-soft": "#1f1f23",
        "ink": "#f0f0f3",
        "ink-secondary": "#c4c4cc",
        "ink-muted": "#8a8a96",
        "ink-subtle": "#55555f",
        "bubble-bot": "#1e1e21",
        "bubble-customer": "#2d3158",
        "bubble-bot-text": "#e0e0ea",
        "bubble-customer-text": "#e8eaff",
        "accent-emerald": "#10b981",
        "accent-amber": "#f59e0b",
        "accent-sky": "#38bdf8",
        "accent-rose": "#fb7185",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        "none": "0px",
        "xs": "4px",

        "xl": "16px",
        "xxl": "20px",
        "pill": "9999px",
        "full": "9999px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        clay: "var(--clay-radius)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "var(--font-inter)", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      backdropBlur: {
        xs: "2px",
        glass: "20px",
        "glass-lg": "32px",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
        "ease-out-expo": "cubic-bezier(0, 0, 0.2, 1)",
      },
      boxShadow: {
        "elev-1": "var(--elev-1)",
        "elev-2": "var(--elev-2)",
        "elev-3": "var(--elev-3)",
        "elev-4": "var(--elev-4)",
        "elev-5": "var(--elev-5)",
        glass: "var(--glass-shadow)",
        clay: "var(--clay-shadow)",
        "glow-primary": "var(--glow-primary)",
        "glow-success": "var(--glow-success)",
        "glow-warning": "var(--glow-warning)",
        "glow-danger": "var(--glow-danger)",
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.5s var(--ps-ease-spring) forwards",
        "scale-in": "scale-in 0.35s var(--ps-ease-spring) forwards",
      },
      backgroundImage: {
        "header-gradient": "var(--bg-header-gradient)",
        "toolpanel-gradient": "var(--bg-toolpanel-gradient)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
